version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\MTD.CouchBot.Domain" 	-c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\MTD.CouchBot.Dals" 		-c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\MTD.CouchBot.Managers" 	-c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\MTD.CouchBot" 		-c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\MTD.CouchBot.Domain"  -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\MTD.CouchBot.Dals" 		 -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\MTD.CouchBot.Managers" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack src\MTD.CouchBot -c Release -o .\artifacts --version-suffix %LABEL%
artifacts:
- path: .\artifacts\*.*
